version: '3.8'

services:
  framework:
    build: .
    command: npm run test-docker -- --host selenium
    links:
      - selenium

  selenium:
    image: selenium/standalone-chrome
    expose:
      - "4444"